waiting
finishWithError: anError
	error := anError.
	self close